name: Invite me to organization
description: Issue to get invited to Hero Programmers organization.
title: "invite me to organization"
labels: ["invite me to organization"]name: Invitation to the GitHub Community Organization
description: I would like to be part of the awesome community
title: "Please invite me to the GitHub Community Organization"
labels: [invite me to the organisation]
body:
  - type: input
    id: name
    attributes:
      label: Name
      placeholder: Insert your name here
    validations:
      required: true
  - type: input
    id: discordname
    attributes:
      label: Discord Username (if applicable)
      placeholder: Insert your Discord username here
    validations:
      required: false
  - type: textarea
    id: Additional
    attributes:
      label: Additional Context
      description: What do you like about this community/Why do you want to join?
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        You can also join our Discord community <a href="https://discord.gg/A8JG8K9TAk">here</a> 
        Feel free to check out other cool repositories of the Hero Programmers Community [here](https://github.com/HeroProgrammers)
